### PR TITLE
Add back forEach method, fix get method, and fix tests

### PR DESCRIPTION
**Pull request by wdoug**
I was a little confused by the spec documentation, but [the MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Headers) defines the forEach method and several browsers definitely support it.

### CODE REVIEW

**Comment by jimmywarting** [comment]
They don't mention it in the spec https://fetch.spec.whatwg.org

**Comment by williamboman** [comment]
Here's an example of usage in the wild:

https://github.com/apollographql/apollo-link-rest/blob/9e5884b7c5bc38b9fe2864dc39e01d21c97b5650/src/restLink.ts#L669-L673

Also, in Chrome:
screenshot 2018-10-25 at 19 10 00

Would be awesome if this was re-added, even though it's not part of the spec.

**Comment by jimmywarting** [comment]
just use the iterator
```js
for (let [key, val] of headers) {
  ...
}
```

**Comment by wdoug** [comment]
I also ended up here because of apollo-link-rest from this issue https://github.com/apollographql/apollo-link-rest/issues/93. What is the goal of this library exactly? Is it just to align exactly with what's in the spec and nothing else? If so, I can update this pull request to just fix the tests and the get method, and include a note in the Readme about it not including a `forEach` method despite how several browsers implement it.

**Comment by jimmywarting** [comment]
> Is it just to align exactly with what's in the spec and nothing else?

yes, it's not available in node-fetch either. so better be consistent so the same code can work in each environment

**Comment by wdoug** [comment]
> it's not available in node-fetch either

[Isn't it though](https://github.com/bitinn/node-fetch/blob/8cc909f5ee725c76dc8d2b0351a04e7e50dfc4ae/src/headers.js#L130-L139)?

**Comment by wdoug** [comment]
Anyway, I updated the PR. Let me know if that seems decent

**Pull request closed without merging**
